Enum Access {
    ADMIN
    HR
    USER
}

Enum StatusUser {
    ACTIVE,
    RESIGN,
    EXPELLED,
    VACUUM,
    DONE
}

Table users {
    id int [pk, increment]
    role_id int
    access Access
    fullname varchar
    
    password varchar
    email varchar
    phones varchar

    is_active bool
    date_start date
    date_end date

    contribution_point float

    last_login_at timestamp

    status StatusUser

    created_at timestamp [note: "when adding new data, fill in the current date"]
    updated_at timestamp [note: "when update data, fill in the current date"]
    created_by int
    updated_by int

    notes text
}

Table roles {
    id int [pk, increment]
    name varchar
    description text
    url_group_wa varchar
    embeded varchar
    deleted_at timestamp
    created_at timestamp [note: "when adding new data, fill in the current date"]
    updated_at date [note: "when update data, fill in the current date"]
    created_by int
    updated_by int
}

Table dailys {
    id int [pk, increment]
    user_id int
    date_activity date
    yesterday text
    today text
    problem text
    created_at timestamp [note: "when adding new data, fill in the current date"]
    email varchar(100)
}

Table warnings {
    id int [pk, increment]
    user_id int
    email varchar
    counter int
    created_at timestamp [note: "when adding new data, fill in the current date"]
    created_by int
}

Enum ProjectStatus {
    NOT_STARTED
    IN_PROGRESS
    COMPLETED
    FIXING
    PUBLISH
}

Enum ProjectType {
    WEB
    MOBILE
    MEDSOS
    GAME
}

Table projects {
    id int [pk, increment]
    pic int
    name varchar
    description text
    status ProjectStatus
    tipe ProjectType
    url_drive varchar
    url_figma varchar
    url_logo varchar
    url_repo varchar
    url_group_wa varchar
    note text
    created_at timestamp [note: "when adding new data, fill in the current date"]
    created_by int
}

Enum StatusSprint {
    PLANNED
    IN_PROGRESS,
    COMPLETED,
    CANCEL
}

Table project_sprints {
    id integer [pk, increment]
    project_id int
    name varchar
    description text
    date_start date
    date_end date
    status StatusSprint
    created_at timestamp [note: "when adding new data, fill in the current date"]
    updated_at date [note: "when update data, fill in the current date"]
    created_by int
    updated_by int
}

Table project_sprint_blacklogs {
    id integer [pk, increment]
    project_id int
    title varchar
    description text
    status StatusSprint
    created_at timestamp [note: "when adding new data, fill in the current date"]
    updated_at date [note: "when update data, fill in the current date"]
    created_by int
    updated_by int
}

Table TypeScheduleMeeting {
    USER
    ROLE
    PROJECT
}

Table schedule_meetings {
    id integer [pk, increment]
    type TypeScheduleMeeting
    meeting_date_start date
    meeting_date_end date
    user_id int
    project_id int
    role_id int
    title varchar
    description text
    location varchar
    created_at timestamp [note: "when adding new data, fill in the current date"]
    updated_at date [note: "when update data, fill in the current date"]
    created_by int
    updated_by int
}

Table schedule_meeting_members {
    id integer [pk, increment]
    schedule_meeting_id int
    user_id int
    created_at timestamp [note: "when adding new data, fill in the current date"]
}

Enum StatusCandidateRequest {
    REQUEST
    OPEN
    CANCEL
    DONE
}

Table candidate_requests {
    id integer [pk, increment]
    role_id integer
    pic_id integer
    total integer
    status StatusCandidateRequest
    description text
    note text
    created_at timestamp [note: "when adding new data, fill in the current date"]
    updated_at date [note: "when update data, fill in the current date"]
    created_by int
    updated_by int
}

Enum StatusCandidates {
    HIRED
    HOLD
    REJECTED
}

Table candidates {
    id integer [pk, increment]
    role_id
    candidate_request_id integer
    nik varchar
    fullname varchar
    email varchar
    phone varchar
    status StatusCandidates
    description text
    created_at timestamp [note: "when adding new data, fill in the current date"]
    updated_at timestamp [note: "when update data, fill in the current date"]
    created_by int
    updated_by int
}

Enum MaritalStatus {
    SINGLE
    MARRIED
    DIVORCED
}

Table employees {
    id integer [pk, increment]
    role_id
    candidate_id integer
    fullname varchar
    nickname varchar
    birth_date date
    birth_place varchar
    marital_status MaritalStatus
    whatsapp_number varchar
    gender tinyint [note: "0: perempuan, 1: laki-laki"]
    religion varchar
    address text
    province varchar
    city varchar
    postcode varchar
    education_latest varchar
    education_institution_name varchar
    education_major varchar
    education_entry_year varchar
    semester varchar
    activity text [note: "Kesibukan"]
    skillset text
    hobby text
    cv varchar
    portofolio varchar
    photo varchar
    url_facebook varchar
    url_x varchar
    url_instagram varchar
    url_tiktok varchar
    url_linkedin varchar
    description text
    status StatusCandidates
    created_at timestamp [note: "when adding new data, fill in the current date"]
    updated_at date [note: "when update data, fill in the current date"]
}

Enum ContractType {
    PROBATION
    CONTRACT
    PERMANENT
    INTERNSHIP
    FREELANCE
    VOLUNTEER
}

Table employee_contracts {
    id integer [pk, increment]
    employee_id int
    type ContractType
    valid_start date
    valid_to date
    is_education_program tinyint
    note text
    created_at timestamp [note: "when adding new data, fill in the current date"]
    updated_at date [note: "when update data, fill in the current date"]
}

Enum EmployeeResignStatus {
    REQUEST,
    REVISED,
    APPROVED,
    CANCELED,
}

Table employee_resigns {
    id integer [pk, increment]
    user_id int
    employee_id int
    status EmployeeResignStatus
    file_resign varchar
    reason text
    approval_id int
    approval_date date
    created_at timestamp [note: "when adding new data, fill in the current date"]
    updated_at date [note: "when update data, fill in the current date"]
    created_by int
    updated_by int
}

Table personal_tasks {
    id integer [pk, increment]
    name varchar
    description text
    counter tinyint
    note text
    deleted_at date
    created_at timestamp [note: "when adding new data, fill in the current date"]
    updated_at date [note: "when update data, fill in the current date"]
    deleted_by int
    created_by int
    updated_by int
}

Table user_personal_tasks {
    id integer [pk, increment]
    user_id int
    personal_task_id int
    date_done date
    notes text
    created_at timestamp [note: "when adding new data, fill in the current date"]
    updated_at date [note: "when update data, fill in the current date"]
    created_by int
    updated_by int
}

// Ref: users.id > dailys.user_id
// Ref: users.id > warnings.user_id